### ISSUE TITLE
Can't 'Add to Cart' from Pdp

### ISSUE THREAD

**Issue by gskerry** [carolynyoo/stack_store#102]
![image](https://cloud.githubusercontent.com/assets/8867156/7424520/35bf2e6e-ef70-11e4-9319-1410216e5f04.png)

![image](https://cloud.githubusercontent.com/assets/8867156/7424521/388c49f6-ef70-11e4-9d63-3aae3f442d9e.png)

POST to api/cart seems to fail from Pdp Controller's addFilmToCart method.

ServerSide errors:
![image](https://cloud.githubusercontent.com/assets/8867156/7424571/e06a8070-ef70-11e4-8691-3dc34167f7f0.png)

**Comment by itsaliu90** [comment]
Hmm, you might have to drop your cart if you already have a strange schema
that exists. Weird.

On Thursday, April 30, 2015, gskerry notifications@github.com wrote:

> [image: image]
> https://cloud.githubusercontent.com/assets/8867156/7424520/35bf2e6e-ef70-11e4-9319-1410216e5f04.png
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/8867156/7424521/388c49f6-ef70-11e4-9d63-3aae3f442d9e.png
> 
> POST to api/cart seems to fail from Pdp Controller's addFilmToCart method.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/carolynyoo/stack_store/issues/102.

## 

Alex Liu
_Account Manager_

Cipher_Health_ http://www.cipherhealth.com/ | @cipherhealth
https://twitter.com/cipherhealth

555 8th Avenue, Suite 701
New York, NY 10018
(585) 662-9096 | aliu@cipherhealth.com

_The information contained in this email message is intended only for use
of the individual or entity named above. If the reader of this message is
not the intended recipient, or the employee or agent responsible to deliver
it to the intended recipient, you are hereby notified that any
dissemination, distribution or copying of this communication is strictly
prohibited. If you have received this communication in error, please
immediately notify me by email (aliu@cipherhealth.com
aliu@cipherhealth.com) and destroy the original message. Thank you._

**Comment by carolynyoo** [comment]
@alexyuningliu yea you're right. i dropped existing cart and it works now

**Comment by gskerry** [comment]
magic. Thanks!
