### ISSUE TITLE
Merge not logged in and logged in cart

### ISSUE THREAD

**Issue by carolynyoo** [carolynyoo/stack_store#115]
@alexyuningliu What happens if I add a film not logged in and then log in and I had previously added other films to my cart? Do the two get merged or does it currently override?

**Comment by itsaliu90** [comment]
The two get merged :) @carolynyoo.
![answer](https://cloud.githubusercontent.com/assets/2261842/7441778/3ca495d4-f092-11e4-8543-5d562e820132.gif)

**Comment by carolynyoo** [comment]
BEAUTIFUL!
