### ISSUE TITLE
Deleting cart item destroys existing data displayed

### ISSUE THREAD

**Issue by darksim735** [carolynyoo/stack_store#74]
![deleting movie causes error](https://cloud.githubusercontent.com/assets/2959633/7338835/79707840-ec26-11e4-87f3-9aa7a8e67580.gif)

**Comment by itsaliu90** [comment]
I'll have a PR for this one in about 10 minutes @darksim735 :).

**Comment by itsaliu90** [comment]
Fixed by: https://github.com/carolynyoo/stack_store/pull/75
