### ISSUE TITLE
Deploy on Heroku!

### ISSUE THREAD

**Issue by itsaliu90** [carolynyoo/stack_store#78]
Instead of waiting until the last minute, we should start configuring the project for easy, continuous deployment to Heroku.

FYI, you'll probably have to do this @carolynyoo since the repo is under your Github account, see:
https://devcenter.heroku.com/articles/github-integration

**Comment by carolynyoo** [comment]
@alexyuningliu YAY! excited to tackle this one

**Comment by carolynyoo** [comment]
![screen shot 2015-04-28 at 7 09 24 pm](https://cloud.githubusercontent.com/assets/8825278/7382209/1c025092-edda-11e4-83c5-3ea6d1e576d1.png)

crash logs...yey
